import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => useContext(LanguageContext)

// Internal category keys (used as filter values in Skills component)
export const SKILL_CATEGORIES = ['All', 'Frontend', 'Backend', 'Data', 'Tools', 'Languages']

// Map from internal key to display label per language
export const categoryLabel = {
  pt: { All: 'Todos', Frontend: 'Frontend', Backend: 'Backend', Data: 'Dados', Tools: 'Ferramentas', Languages: 'Idiomas' },
  en: { All: 'All', Frontend: 'Frontend', Backend: 'Backend', Data: 'Data', Tools: 'Tools', Languages: 'Languages' },
  es: { All: 'Todos', Frontend: 'Frontend', Backend: 'Backend', Data: 'Datos', Tools: 'Herramientas', Languages: 'Idiomas' },
}

export const translations = {
  pt: {
    code: 'pt',
    flag: '🇧🇷',
    label: 'Português',
    nav: {
      home: 'Início',
      about: 'Sobre',
      skills: 'Habilidades',
      projects: 'Projetos',
      experience: 'Experiência',
      education: 'Formação',
      contact: 'Contato',
      cta: 'Fale comigo',
    },
    hero: {
      greeting: 'Olá, eu sou',
      studentOf: 'Estudante de',
      inThe: 'no',
      course: 'Sistemas de Informação',
      semester: '7º semestre',
      semesterSuffix: ', apaixonado por tecnologia e desenvolvimento de soluções inovadoras.',
      btnProjects: 'Ver Projetos',
      btnContact: 'Fale comigo',
      scroll: 'scroll',
      roles: ['Estudante de SI', 'Desenvolvedor Web', 'Programador Python', 'Entusiasta de Tech'],
    },
    about: {
      tag: '// quem sou eu',
      title: 'Sobre Mim',
      subtitle: 'Conheça um pouco mais sobre minha jornada',
      bio: [
        'Olá! Sou <span class="text-white font-semibold">Claudio Santos</span>, estudante de <span class="text-primary font-semibold">Sistemas de Informação</span> no <span class="text-white font-semibold">7º semestre</span>, com grande paixão pelo desenvolvimento de software e pela tecnologia em geral.',
        'Ao longo da minha formação, adquiri experiência prática em diversas tecnologias, desde o desenvolvimento <span class="text-secondary font-semibold">front-end e back-end</span> até análise de dados e automação. Tenho buscado sempre evoluir e me manter atualizado com as tendências do mercado.',
        'Tenho habilidades sólidas em <span class="text-primary font-semibold">HTML, CSS, JavaScript, PHP e React</span> no front-end/back-end, além de <span class="text-white font-semibold">Python e SQL</span> para automação e banco de dados.',
        'Também possuo conhecimentos em <span class="text-primary font-semibold">Excel avançado</span> e <span class="text-white font-semibold">Inglês básico</span>, suficiente para leitura de documentações e conteúdos técnicos.',
      ],
      stats: ['Semestre', 'Tecnologias', 'Anos estudando', 'Inglês'],
      statValues: ['7º', '9+', '4+', 'Básico'],
      highlights: [
        { title: 'Desenvolvimento Web', description: 'Criação de interfaces modernas e responsivas com as melhores tecnologias do mercado.' },
        { title: 'Banco de Dados', description: 'Modelagem e gerenciamento de dados com SQL para soluções eficientes e escaláveis.' },
        { title: 'Resolução de Problemas', description: 'Análise crítica e busca por soluções criativas para desafios tecnológicos.' },
      ],
    },
    skills: {
      tag: '// o que eu sei fazer',
      title: 'Habilidades',
      subtitle: 'Tecnologias e ferramentas que utilizo no dia a dia',
      stackTitle: 'Stack Completa',
    },
    projects: {
      tag: '// o que eu construí',
      title: 'Projetos',
      subtitle: 'Alguns dos projetos que desenvolvi ao longo da minha trajetória',
      featured: 'Destaque',
      code: 'Código',
      liveDemo: 'Demo ao vivo',
      manual: 'Manual',
      drivePage: 'Página do Drive',
      addHint: '// Para adicionar projetos, edite o arquivo:',
      addSub: 'Adicione um novo objeto no array',
      items: [
        { title: 'Sistema de Driver', description: 'Sistema web completo para gerenciamento de drivers, com controle de cadastro, rotas e status em tempo real.' },
        { title: 'Sistema de Kanban', description: 'Aplicação de gerenciamento de tarefas no estilo Kanban, com colunas arrastáveis, prioridades e controle de fluxo de trabalho.' },
        { title: 'Sistema de Abertura de Chamado HelpDesk', description: 'Sistema web para abertura, acompanhamento e resolução de chamados de suporte técnico, com painel de administração e histórico.' },
      ],
    },
    experience: {
      tag: '// onde já trabalhei',
      title: 'Experiência Profissional',
      subtitle: 'Minha trajetória no mercado de trabalho',
      current: 'Atual',
      items: [
        {
          role: 'Estagiário em Suporte',
          company: 'Vem Sorrir Implantes Odontológicos',
          period: 'Setembro 2025 – Presente',
          location: 'Brasil',
          type: 'Estágio',
          description: 'Atuação em suporte técnico, atendimento de chamados, resolução de problemas e auxílio a usuários internos e externos. Desenvolvimento de habilidades em análise e resolução de incidentes de TI.',
          tags: ['Suporte Técnico', 'TI', 'Helpdesk', 'Atendimento'],
        },
        {
          role: 'Desenvolvedor de Agentes de IA & Desenvolvedor Web',
          company: 'Virtues Apps',
          period: 'Junho 2025 – Setembro 2025',
          location: 'Brasil',
          type: 'Desenvolvedor',
          description: 'Desenvolvimento de agentes de inteligência artificial para automação de processos e criação de aplicações web. Trabalho com integração de APIs, desenvolvimento front-end e back-end e implementação de soluções baseadas em IA.',
          tags: ['Agentes de IA', 'Desenvolvimento Web', 'Python', 'JavaScript', 'APIs'],
        },
      ],
    },
    education: {
      tag: '// minha trajetória',
      title: 'Formação',
      subtitle: 'Educação e cursos que moldaram meu conhecimento',
      ongoing: 'Em andamento',
      items: [
        {
          title: 'Bacharelado em Sistemas de Informação',
          institution: 'Universidade Santa Cecília',
          period: '2023 – Presente',
          location: 'Brasil',
          description: 'Cursando o 7º semestre. Aprendizado em programação, Banco de Dados, Redes, Engenharia de Software, Sistemas Operacionais e muito mais.',
          tags: ['Programação', 'BD', 'Redes', 'Eng. Software'],
        },
        {
          title: 'Excel Básico',
          institution: 'Curso Online',
          period: '06/09/2024 – 09/09/2024',
          location: 'Online',
          description: 'Fundamentos do Microsoft Excel: navegação, fórmulas básicas, formatação de planilhas e organização de dados.',
          tags: ['Excel', 'Planilhas', 'Fórmulas'],
        },
        {
          title: 'Excel Intermediário',
          institution: 'Curso Online',
          period: '12/09/2024 – 13/09/2024',
          location: 'Online',
          description: 'Funções avançadas, tabelas dinâmicas, gráficos e recursos de produtividade no Excel.',
          tags: ['Excel', 'Tabelas Dinâmicas', 'Gráficos'],
        },
        {
          title: 'Excel Avançado',
          institution: 'Curso Online',
          period: '01/10/2024 – 04/10/2024',
          location: 'Online',
          description: 'Macros, VBA, automação de tarefas e dashboards profissionais no Excel.',
          tags: ['Excel', 'VBA', 'Macros', 'Dashboard'],
        },
        {
          title: 'Site com HTML, CSS e JavaScript',
          institution: 'Curso Online',
          period: '21/08/2024 – 28/08/2024',
          location: 'Online',
          description: 'Desenvolvimento de sites estáticos com HTML, CSS e JavaScript, incluindo layouts responsivos e interatividade.',
          tags: ['HTML', 'CSS', 'JavaScript'],
        },
        {
          title: 'Python Básico',
          institution: 'Curso Online',
          period: '28/08/2024 – 30/08/2024',
          location: 'Online',
          description: 'Introdução à linguagem Python: variáveis, estruturas de controle, funções e lógica de programação.',
          tags: ['Python', 'Lógica', 'Programação'],
        },
        {
          title: 'JavaScript',
          institution: 'Curso Online',
          period: 'Concluído em 08/07/2024',
          location: 'Online',
          description: 'Domínio de JavaScript: manipulação do DOM, eventos, funções e conceitos essenciais da linguagem.',
          tags: ['JavaScript', 'DOM', 'Web'],
        },
        {
          title: 'HTML5 e CSS3',
          institution: 'Curso Online',
          period: 'Concluído em 27/08/2024',
          location: 'Online',
          description: 'Construção de páginas web modernas com HTML5 semântico e CSS3 com animações e layout responsivo.',
          tags: ['HTML5', 'CSS3', 'Responsivo'],
        },
        {
          title: 'Administrando Banco de Dados',
          institution: 'Curso Online',
          period: '30/08/2024 – 04/09/2024',
          location: 'Online',
          description: 'Administração de banco de dados relacional: consultas SQL, modelagem, backup e manutenção de dados.',
          tags: ['SQL', 'Banco de Dados', 'MySQL'],
        },
      ],
    },
    contact: {
      tag: '// vamos conversar',
      title: 'Contato',
      subtitle: 'Entre em contato para projetos, colaborações ou só um papo sobre tech!',
      cardTitle: 'Vamos trabalhar juntos?',
      cardText: 'Tem uma ideia, um projeto ou só quer trocar uma ideia sobre tecnologia? Me manda uma mensagem, vai ser um prazer conversar!',
      socials: 'Me encontre nas redes:',
      formTitle: 'Envie uma mensagem',
      name: 'Nome',
      namePlaceholder: 'Seu nome completo',
      email: 'Email',
      emailPlaceholder: 'seuemail@email.com',
      message: 'Mensagem',
      messagePlaceholder: 'Olá! Gostaria de conversar sobre...',
      send: 'Enviar mensagem',
      sending: 'Enviando...',
      success: 'Mensagem enviada! Entrarei em contato em breve.',
      error: 'Erro ao enviar. Tente novamente ou use o WhatsApp.',
    },
    certificates: {
      tag: '// certificados',
      title: 'Certificados',
      subtitle: 'Cursos e certificações concluídos ao longo da minha jornada',
      items: [
        { name: 'JavaScript Completo', cardName: 'JavaScript', issuer: 'Curso em Vídeo', year: '2024', color: '#F7DF1E', tag: 'Web', image: '/certs/javascript-completo.jpg', url: '#' },
        { name: 'HTML5 e CSS3 Completo', cardName: 'HTML5 + CSS3', issuer: 'Curso em Vídeo', year: '2024', color: '#E34F26', tag: 'Web', image: '/certs/html-css-completo.jpg', url: '#' },
        { name: 'Linguagem de Programação Python Básico', cardName: 'Python', issuer: 'Bradesco Cursos', year: '2024', color: '#3776AB', tag: 'Python', image: '/certs/python-basico.jpg', url: '#' },
        { name: 'Excel Básico', cardName: 'Excel', issuer: 'Bradesco Cursos', year: '2024', color: '#217346', tag: 'Dados', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Excel Intermediário', cardName: 'Excel', issuer: 'Bradesco Cursos', year: '2024', color: '#217346', tag: 'Dados', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Excel Avançado', cardName: 'Excel', issuer: 'Bradesco Cursos', year: '2024', color: '#217346', tag: 'Dados', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Site Simples com HTML, CSS e JS', cardName: 'Website HTML/CSS/JS', issuer: 'Bradesco Cursos', year: '2024', color: '#6C63FF', tag: 'Web', image: '/certs/website-html-css-js.jpg', url: '#' },
        { name: 'Administrando Banco de Dados', cardName: 'Banco de Dados', issuer: 'Bradesco Cursos', year: '2024', color: '#cfdd08', tag: 'SQL', image: '/certs/banco-dados-sql.jpg', url: '#' },
      ],
    },
    footer: {
      madeWith: 'Feito com',
      using: 'usando React + Tailwind CSS',
    },
  },

  en: {
    code: 'en',
    flag: '🇺🇸',
    label: 'English',
    nav: {
      home: 'Home',
      about: 'About',
      skills: 'Skills',
      projects: 'Projects',
      experience: 'Experience',
      education: 'Education',
      contact: 'Contact',
      cta: 'Get in touch',
    },
    hero: {
      greeting: "Hi, I'm",
      studentOf: 'Student of',
      inThe: 'in the',
      course: 'Information Systems',
      semester: '7th semester',
      semesterSuffix: ', passionate about technology and building innovative solutions.',
      btnProjects: 'View Projects',
      btnContact: 'Get in touch',
      scroll: 'scroll',
      roles: ['IS Student', 'Web Developer', 'Python Programmer', 'Tech Enthusiast'],
    },
    about: {
      tag: '// who I am',
      title: 'About Me',
      subtitle: 'Get to know a little more about my journey',
      bio: [
        "Hi! I'm <span class=\"text-white font-semibold\">Claudio Santos</span>, a student of <span class=\"text-primary font-semibold\">Information Systems</span> in my <span class=\"text-white font-semibold\">7th semester</span>, with a great passion for software development and technology.",
        "Throughout my studies I gained hands-on experience with various technologies, from <span class=\"text-secondary font-semibold\">front-end and back-end development</span> to data analysis and automation. I'm always striving to grow and keep up with market trends.",
        'I have solid skills in <span class="text-primary font-semibold">HTML, CSS, JavaScript, PHP and React</span> for front/back-end, as well as <span class="text-white font-semibold">Python and SQL</span> for automation and databases.',
        'I also have knowledge in <span class="text-primary font-semibold">advanced Excel</span> and <span class="text-white font-semibold">basic English</span>, enough for reading documentation and technical content.',
      ],
      stats: ['Semester', 'Technologies', 'Years studying', 'English'],
      statValues: ['7th', '9+', '4+', 'Basic'],
      highlights: [
        { title: 'Web Development', description: 'Building modern and responsive interfaces with the best market technologies.' },
        { title: 'Databases', description: 'Data modeling and management with SQL for efficient and scalable solutions.' },
        { title: 'Problem Solving', description: 'Critical analysis and creative solutions for technological challenges.' },
      ],
    },
    skills: {
      tag: '// what I can do',
      title: 'Skills',
      subtitle: 'Technologies and tools I use on a daily basis',
      stackTitle: 'Full Stack',
    },
    projects: {
      tag: '// what I built',
      title: 'Projects',
      subtitle: 'Some of the projects I developed throughout my journey',
      featured: 'Featured',
      code: 'Code',
      liveDemo: 'Live Demo',
      manual: 'Manual',
      drivePage: 'Drive Page',
      addHint: '// To add projects, edit the file:',
      addSub: 'Add a new object to the array',
      items: [
        { title: 'Driver System', description: 'Complete web system for driver management with registration control, routes and real-time status tracking.' },
        { title: 'Kanban System', description: 'Kanban-style task management application with draggable columns, priorities and workflow control.' },
        { title: 'HelpDesk Ticket System', description: 'Web system for opening, tracking and resolving technical support tickets, with admin panel and ticket history.' },
      ],
    },
    experience: {
      tag: '// where I worked',
      title: 'Professional Experience',
      subtitle: 'My journey in the job market',
      current: 'Current',
      items: [
        {
          role: 'IT Support Intern',
          company: 'Vem Sorrir Implantes Odontológicos',
          period: 'September 2025 – Present',
          location: 'Brazil',
          type: 'Internship',
          description: 'Technical support, ticket handling, troubleshooting and assisting internal and external users. Developing skills in IT incident analysis and resolution.',
          tags: ['Technical Support', 'IT', 'Helpdesk', 'Customer Service'],
        },
        {
          role: 'AI Agent Developer & Web Developer',
          company: 'Virtues Apps',
          period: 'June 2025 – September 2025',
          location: 'Brazil',
          type: 'Internship',
          description: 'Development of artificial intelligence agents for process automation and web application creation. Working with API integration, front-end and back-end development and implementation of AI-based solutions.',
          tags: ['AI Agents', 'Web Development', 'Python', 'JavaScript', 'APIs'],
        },
      ],
    },
    education: {
      tag: '// my journey',
      title: 'Education',
      subtitle: 'Education and courses that shaped my knowledge',
      ongoing: 'Ongoing',
      items: [
        {
          title: 'Bachelor in Information Systems',
          institution: 'Universidade Santa Cecília',
          period: '2023 – Present',
          location: 'Brazil',
          description: 'Currently in the 7th semester. Learning programming, Databases, Networks, Software Engineering, Operating Systems and much more.',
          tags: ['Programming', 'DB', 'Networks', 'Soft. Eng.'],
        },
        {
          title: 'Basic Excel',
          institution: 'Online Course',
          period: '06/09/2024 – 09/09/2024',
          location: 'Online',
          description: 'Microsoft Excel fundamentals: navigation, basic formulas, spreadsheet formatting and data organization.',
          tags: ['Excel', 'Spreadsheets', 'Formulas'],
        },
        {
          title: 'Intermediate Excel',
          institution: 'Online Course',
          period: '12/09/2024 – 13/09/2024',
          location: 'Online',
          description: 'Advanced functions, pivot tables, charts and productivity features in Excel.',
          tags: ['Excel', 'Pivot Tables', 'Charts'],
        },
        {
          title: 'Advanced Excel',
          institution: 'Online Course',
          period: '01/10/2024 – 04/10/2024',
          location: 'Online',
          description: 'Macros, VBA, task automation and professional dashboards in Excel.',
          tags: ['Excel', 'VBA', 'Macros', 'Dashboard'],
        },
        {
          title: 'Website with HTML, CSS and JavaScript',
          institution: 'Online Course',
          period: '21/08/2024 – 28/08/2024',
          location: 'Online',
          description: 'Building static websites with HTML, CSS and JavaScript, including responsive layouts and interactivity.',
          tags: ['HTML', 'CSS', 'JavaScript'],
        },
        {
          title: 'Basic Python',
          institution: 'Online Course',
          period: '28/08/2024 – 30/08/2024',
          location: 'Online',
          description: 'Introduction to Python: variables, control structures, functions and programming logic.',
          tags: ['Python', 'Logic', 'Programming'],
        },
        {
          title: 'JavaScript',
          institution: 'Online Course',
          period: 'Completed on 08/07/2024',
          location: 'Online',
          description: 'JavaScript mastery: DOM manipulation, events, functions and essential language concepts.',
          tags: ['JavaScript', 'DOM', 'Web'],
        },
        {
          title: 'HTML5 and CSS3',
          institution: 'Online Course',
          period: 'Completed on 27/08/2024',
          location: 'Online',
          description: 'Building modern web pages with semantic HTML5 and CSS3 with animations and responsive layout.',
          tags: ['HTML5', 'CSS3', 'Responsive'],
        },
        {
          title: 'Database Administration',
          institution: 'Online Course',
          period: '30/08/2024 – 04/09/2024',
          location: 'Online',
          description: 'Relational database administration: SQL queries, modeling, backup and data maintenance.',
          tags: ['SQL', 'Database', 'MySQL'],
        },
      ],
    },
    contact: {
      tag: "// let's talk",
      title: 'Contact',
      subtitle: 'Get in touch for projects, collaborations or just a tech chat!',
      cardTitle: "Let's work together?",
      cardText: 'Have an idea, a project, or just want to chat about tech? Send me a message — it will be a pleasure to talk!',
      socials: 'Find me on:',
      formTitle: 'Send a message',
      name: 'Name',
      namePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'youremail@email.com',
      message: 'Message',
      messagePlaceholder: 'Hi! I would like to talk about...',
      send: 'Send message',
      sending: 'Sending...',
      success: 'Message sent! I will get back to you soon.',
      error: 'Error sending. Please try again or use WhatsApp.',
    },
    certificates: {
      tag: '// certificates',
      title: 'Certificates',
      subtitle: 'Courses and certifications completed throughout my journey',
      items: [
        { name: 'Complete JavaScript', cardName: 'JavaScript', issuer: 'Bradesco Courses', year: '2024', color: '#F7DF1E', tag: 'Web', image: '/certs/javascript-completo.jpg', url: '#' },
        { name: 'Complete HTML5 and CSS3', cardName: 'HTML5 + CSS3', issuer: 'Bradesco Courses', year: '2024', color: '#E34F26', tag: 'Web', image: '/certs/html-css-completo.jpg', url: '#' },
        { name: 'Basic Python Programming Language', cardName: 'Python', issuer: 'Bradesco Courses', year: '2024', color: '#3776AB', tag: 'Python', image: '/certs/python-basico.jpg', url: '#' },
        { name: 'Basic Excel', cardName: 'Excel', issuer: 'Bradesco Courses', year: '2024', color: '#217346', tag: 'Data', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Intermediate Excel', cardName: 'Excel', issuer: 'Bradesco Courses', year: '2024', color: '#217346', tag: 'Data', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Advanced Excel', cardName: 'Excel', issuer: 'Bradesco Courses', year: '2024', color: '#217346', tag: 'Data', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Simple Website with HTML, CSS and JS', cardName: 'HTML/CSS/JS Website', issuer: 'Bradesco Courses', year: '2024', color: '#6C63FF', tag: 'Web', image: '/certs/website-html-css-js.jpg', url: '#' },
        { name: 'Database Administration', cardName: 'Databases', issuer: 'Bradesco Courses', year: '2024', color: '#cfdd08', tag: 'SQL', image: '/certs/banco-dados-sql.jpg', url: '#' },
      ],
    },
    footer: {
      madeWith: 'Made with',
      using: 'using React + Tailwind CSS',
    },
  },

  es: {
    code: 'es',
    flag: '🇪🇸',
    label: 'Español',
    nav: {
      home: 'Inicio',
      about: 'Sobre mí',
      skills: 'Habilidades',
      projects: 'Proyectos',
      experience: 'Experiencia',
      education: 'Formación',
      contact: 'Contacto',
      cta: 'Contáctame',
    },
    hero: {
      greeting: 'Hola, soy',
      studentOf: 'Estudiante de',
      inThe: 'en el',
      course: 'Sistemas de Información',
      semester: '7º semestre',
      semesterSuffix: ', apasionado por la tecnología y el desarrollo de soluciones innovadoras.',
      btnProjects: 'Ver Proyectos',
      btnContact: 'Contáctame',
      scroll: 'scroll',
      roles: ['Estudiante de SI', 'Desarrollador Web', 'Programador Python', 'Entusiasta Tech'],
    },
    about: {
      tag: '// quién soy',
      title: 'Sobre Mí',
      subtitle: 'Conoce un poco más sobre mi trayectoria',
      bio: [
        '¡Hola! Soy <span class="text-white font-semibold">Claudio Santos</span>, estudiante de <span class="text-primary font-semibold">Sistemas de Información</span> en el <span class="text-white font-semibold">7º semestre</span>, con gran pasión por el desarrollo de software y la tecnología.',
        'A lo largo de mi formación adquirí experiencia práctica en diversas tecnologías, desde el <span class="text-secondary font-semibold">desarrollo front-end y back-end</span> hasta el análisis de datos y la automatización. Siempre busco crecer y mantenerme actualizado.',
        'Tengo habilidades sólidas en <span class="text-primary font-semibold">HTML, CSS, JavaScript, PHP y React</span> para front/back-end, además de <span class="text-white font-semibold">Python y SQL</span> para automatización y bases de datos.',
        'También tengo conocimientos en <span class="text-primary font-semibold">Excel avanzado</span> e <span class="text-white font-semibold">inglés básico</span>, suficiente para leer documentación y contenidos técnicos.',
      ],
      stats: ['Semestre', 'Tecnologías', 'Años estudiando', 'Inglés'],
      statValues: ['7º', '9+', '4+', 'Básico'],
      highlights: [
        { title: 'Desarrollo Web', description: 'Creación de interfaces modernas y responsivas con las mejores tecnologías del mercado.' },
        { title: 'Bases de Datos', description: 'Modelado y gestión de datos con SQL para soluciones eficientes y escalables.' },
        { title: 'Resolución de Problemas', description: 'Análisis crítico y búsqueda de soluciones creativas para desafíos tecnológicos.' },
      ],
    },
    skills: {
      tag: '// qué sé hacer',
      title: 'Habilidades',
      subtitle: 'Tecnologías y herramientas que uso en el día a día',
      stackTitle: 'Stack Completo',
    },
    projects: {
      tag: '// lo que construí',
      title: 'Proyectos',
      subtitle: 'Algunos de los proyectos que desarrollé a lo largo de mi trayectoria',
      featured: 'Destacado',
      code: 'Código',
      liveDemo: 'Demo en vivo',
      manual: 'Manual',
      drivePage: 'Página del Drive',
      addHint: '// Para agregar proyectos, edita el archivo:',
      addSub: 'Agrega un nuevo objeto en el array',
      items: [
        { title: 'Sistema de Driver', description: 'Sistema web completo para gestión de drivers, con control de registro, rutas y estado en tiempo real.' },
        { title: 'Sistema Kanban', description: 'Aplicación de gestión de tareas estilo Kanban con columnas arrastrables, prioridades y control de flujo de trabajo.' },
        { title: 'Sistema de Tickets HelpDesk', description: 'Sistema web para apertura, seguimiento y resolución de tickets de soporte técnico, con panel de administración e historial.' },
      ],
    },
    experience: {
      tag: '// dónde trabajé',
      title: 'Experiencia Profesional',
      subtitle: 'Mi trayectoria en el mercado laboral',
      current: 'Actual',
      items: [
        {
          role: 'Practicante de Soporte TI',
          company: 'Vem Sorrir Implantes Odontológicos',
          period: 'Septiembre 2025 – Presente',
          location: 'Brasil',
          type: 'Prácticas',
          description: 'Soporte técnico, atención de tickets, resolución de problemas y asistencia a usuarios internos y externos. Desarrollo de habilidades en análisis y resolución de incidentes de TI.',
          tags: ['Soporte Técnico', 'TI', 'Helpdesk', 'Atención al cliente'],
        },
        {
          role: 'Desarrollador de Agentes de IA & Desarrollador Web',
          company: 'Virtues Apps',
          period: 'Junio 2025 – Septiembre 2025',
          location: 'Brasil',
          type: 'Prácticas',
          description: 'Desarrollo de agentes de inteligencia artificial para automatización de procesos y creación de aplicaciones web. Trabajo con integración de APIs, desarrollo front-end y back-end e implementación de soluciones basadas en IA.',
          tags: ['Agentes de IA', 'Desarrollo Web', 'Python', 'JavaScript', 'APIs'],
        },
      ],
    },
    education: {
      tag: '// mi trayectoria',
      title: 'Formación',
      subtitle: 'Educación y cursos que moldearon mi conocimiento',
      ongoing: 'En curso',
      items: [
        {
          title: 'Licenciatura en Sistemas de Información',
          institution: 'Universidade Santa Cecília',
          period: '2023 – Presente',
          location: 'Brasil',
          description: 'Cursando el 7º semestre. Aprendizaje en programación, Bases de Datos, Redes, Ingeniería de Software, Sistemas Operativos y mucho más.',
          tags: ['Programación', 'BD', 'Redes', 'Ing. Software'],
        },
        {
          title: 'Excel Básico',
          institution: 'Curso Online',
          period: '06/09/2024 – 09/09/2024',
          location: 'Online',
          description: 'Fundamentos de Microsoft Excel: navegación, fórmulas básicas, formato de hojas de cálculo y organización de datos.',
          tags: ['Excel', 'Hojas de cálculo', 'Fórmulas'],
        },
        {
          title: 'Excel Intermedio',
          institution: 'Curso Online',
          period: '12/09/2024 – 13/09/2024',
          location: 'Online',
          description: 'Funciones avanzadas, tablas dinámicas, gráficos y recursos de productividad en Excel.',
          tags: ['Excel', 'Tablas Dinámicas', 'Gráficos'],
        },
        {
          title: 'Excel Avanzado',
          institution: 'Curso Online',
          period: '01/10/2024 – 04/10/2024',
          location: 'Online',
          description: 'Macros, VBA, automatización de tareas y dashboards profesionales en Excel.',
          tags: ['Excel', 'VBA', 'Macros', 'Dashboard'],
        },
        {
          title: 'Sitio web con HTML, CSS y JavaScript',
          institution: 'Curso Online',
          period: '21/08/2024 – 28/08/2024',
          location: 'Online',
          description: 'Desarrollo de sitios estáticos con HTML, CSS y JavaScript, incluyendo layouts responsivos e interactividad.',
          tags: ['HTML', 'CSS', 'JavaScript'],
        },
        {
          title: 'Python Básico',
          institution: 'Curso Online',
          period: '28/08/2024 – 30/08/2024',
          location: 'Online',
          description: 'Introducción a Python: variables, estructuras de control, funciones y lógica de programación.',
          tags: ['Python', 'Lógica', 'Programación'],
        },
        {
          title: 'JavaScript',
          institution: 'Curso Online',
          period: 'Completado el 08/07/2024',
          location: 'Online',
          description: 'Dominio de JavaScript: manipulación del DOM, eventos, funciones y conceptos esenciales del lenguaje.',
          tags: ['JavaScript', 'DOM', 'Web'],
        },
        {
          title: 'HTML5 y CSS3',
          institution: 'Curso Online',
          period: 'Completado el 27/08/2024',
          location: 'Online',
          description: 'Construcción de páginas web modernas con HTML5 semántico y CSS3 con animaciones y layout responsivo.',
          tags: ['HTML5', 'CSS3', 'Responsivo'],
        },
        {
          title: 'Administración de Bases de Datos',
          institution: 'Curso Online',
          period: '30/08/2024 – 04/09/2024',
          location: 'Online',
          description: 'Administración de bases de datos relacionales: consultas SQL, modelado, backup y mantenimiento de datos.',
          tags: ['SQL', 'Base de Datos', 'MySQL'],
        },
      ],
    },
    contact: {
      tag: '// hablemos',
      title: 'Contacto',
      subtitle: '¡Contáctame para proyectos, colaboraciones o solo una charla sobre tecnología!',
      cardTitle: '¿Trabajamos juntos?',
      cardText: '¿Tienes una idea, un proyecto o solo quieres charlar sobre tecnología? ¡Envíame un mensaje, será un placer conversar!',
      socials: 'Encuéntrame en:',
      formTitle: 'Envía un mensaje',
      name: 'Nombre',
      namePlaceholder: 'Tu nombre completo',
      email: 'Email',
      emailPlaceholder: 'tuemail@email.com',
      message: 'Mensaje',
      messagePlaceholder: '¡Hola! Me gustaría hablar sobre...',
      send: 'Enviar mensaje',
      sending: 'Enviando...',
      success: '¡Mensaje enviado! Me pondré en contacto pronto.',
      error: 'Error al enviar. Inténtalo de nuevo o usa WhatsApp.',
    },
    certificates: {
      tag: '// certificados',
      title: 'Certificados',
      subtitle: 'Cursos y certificaciones completados a lo largo de mi trayectoria',
      items: [
        { name: 'JavaScript Completo', cardName: 'JavaScript', issuer: 'Cursos Bradesco', year: '2024', color: '#F7DF1E', tag: 'Web', image: '/certs/javascript-completo.jpg', url: '#' },
        { name: 'HTML5 y CSS3 Completo', cardName: 'HTML5 + CSS3', issuer: 'Cursos Bradesco', year: '2024', color: '#E34F26', tag: 'Web', image: '/certs/html-css-completo.jpg', url: '#' },
        { name: 'Lenguaje de Programación Python Básico', cardName: 'Python', issuer: 'Cursos Bradesco', year: '2024', color: '#3776AB', tag: 'Python', image: '/certs/python-basico.jpg', url: '#' },
        { name: 'Excel Básico', cardName: 'Excel', issuer: 'Cursos Bradesco', year: '2024', color: '#217346', tag: 'Datos', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Excel Intermedio', cardName: 'Excel', issuer: 'Cursos Bradesco', year: '2024', color: '#217346', tag: 'Datos', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Excel Avanzado', cardName: 'Excel', issuer: 'Cursos Bradesco', year: '2024', color: '#217346', tag: 'Datos', image: '/certs/excel-vba.jpg', url: '#' },
        { name: 'Sitio Simple con HTML, CSS y JS', cardName: 'Sitio HTML/CSS/JS', issuer: 'Cursos Bradesco', year: '2024', color: '#6C63FF', tag: 'Web', image: '/certs/website-html-css-js.jpg', url: '#' },
        { name: 'Administración de Bases de Datos', cardName: 'Base de Datos', issuer: 'Cursos Bradesco', year: '2024', color: '#cfdd08', tag: 'SQL', image: '/certs/banco-dados-sql.jpg', url: '#' },
      ],
    },
    footer: {
      madeWith: 'Hecho con',
      using: 'usando React + Tailwind CSS',
    },
  },
}

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('pt')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  )
}
